import BarrierVerification.FiniteWindowRealization

#print axioms BarrierVerification.matrixCommonAtomOfRealization
#print axioms BarrierVerification.reverseWindowFamily_linearIndependent
#print axioms BarrierVerification.matrixQuotientFunctional_jointNondegenerate
